name: faces-api
channels:
  - default
  - menpo
  - pytorch
dependencies:
  - matplotlib=3.0.3
  - pytorch=1.1.0
  - torchvision=0.3.0
  - scikit-image=0.15.0
  - scipy=1.2.1
  - tqdm=4.31.1
  - pip:
    - tensorflow==1.13.1
    - keras
